### ISSUE TITLE
Auto change other nodes to Ignore when Match selected

### ISSUE THREAD

**Issue by hmnd** [tjhorner/gtfs-janitor#6]
When Match is selected for a node, set all other node options to Ignore automatically.

**Comment by tjhorner** [comment]
If a new match is selected while a different node is already matched, it will swap their states. This is useful, for example, if duplicate nodes were detected and it automatically selected one for deletion, but the other node actually makes more sense to use.

https://github.com/user-attachments/assets/7a262e84-1161-4bfd-8dfb-a0d752a4585e
